version: '2'
services:
  drupal:
    user: "1000000"
    hostname: drupal
    build: .
    image: ubuntu-16-apache-php-5.6-drupal-7
    environment:
      DRUPAL_DB_USER: fhtest
      DRUPAL_DB_PASSWORD: Fhtest123!
      DRUPAL_DB_NAME: fhtest
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - mysql
    links:
      - mysql

# Using official mysql for testing, this will need changing to our mysql/mariadb when ready.
  mysql:
    hostname: mysql
    image: 1and1internet/ubuntu-16-nginx-php-phpmyadmin-mysql-5:latest
    user: "1000000"
    environment:
      MYSQL_USER: fhtest
      MYSQL_PASSWORD: Fhtest123!
      MYSQL_DATABASE: fhtest
      MYSQL_ROOT_PASSWORD: bob
      SUPERVISORD_EXIT_ON_FATAL: "0"    
    ports:
      - "8081:8080"
